
version: "3.8"

services:
  traefik:
    image: traefik:v2.5
    networks:
      - default
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      --api.insecure=true 
      --providers.docker
      --entrypoints.web.address=:80

networks:
  default:
    external: false
    name: traefik_network