
version: "3.8"

services:
  traefik:
    image: traefik:v2.5
    networks:
      - default
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: false
    name: traefik_network