version: '3.8'

services:

  pgadmin:
      image: dpage/pgadmin4:${PG_VERSION}
      restart: always
      networks:
        - default
        - postgres_network
        - nginx_network
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        VIRTUAL_HOST: pgadmin.local.com
        VIRTUAL_PORT: 80
      #ports:
        #- 8080:80
    
      

  adminer:
      image: adminer:${ADMINER_VERSION}
      networks:
        - default
        - database_network
        - moud-network
        - nginx_network
      container_name: adminer_container
      restart: always
      #ports:
        #- 8081:8080
      environment:
        VIRTUAL_HOST: adminer.local.com
        VIRTUAL_PORT: 8080

networks:
  default:
    name: db_explorer
    external: false
  database_network:
    external: true
  postgres_network:
    external: true
  moud-network:
    external: true
  nginx_network:
    external: true
