#docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro nginxproxy/nginx-proxy

version: '3.8'

services:

  nginx:
    image:  nginxproxy/nginx-proxy:1.3-alpine
    networks:
      - default
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    name: nginx_network
    external: false
