version: "3.8"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    networks:
      - default
      - nginx_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VIRTUAL_HOST=home.local.com
      - VIRTUAL_PORT=80
    volumes:
      - ./config:/config
    restart: unless-stopped

networks:
  default:
    external: false
    name: heimdall_network
  nginx_network:
    external: true