version: "3"

networks:
  gitea:
    external: false
  nginx_network:
      external: true

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - VIRTUAL_HOST=git.local.com
      - VIRTUAL_PORT=3000
    restart: always
    networks:
      - gitea
      - nginx_network
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


    

